# fly.toml app configuration file for D&D Campaign Builder with LiteFS
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'dnd-companion'
primary_region = 'lhr'
console_command = '/entrypoint.sh manage.py shell'

[build]

[env]
# Django configuration
DJANGO_DEBUG = "false"
DJANGO_SETTINGS_MODULE = "dnd_companion.settings"
PRIMARY_REGION = "lhr"

# LiteFS configuration
LITEFS_DIR = "/litefs"

# Application settings
PORT = "8000"

[experimental]
enable_consul = true

# Main HTTP service (proxied through LiteFS)
[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

# Health check configuration
[[http_service.checks]]
grace_period = "30s"
interval = "15s"
method = "GET"
path = "/"
timeout = "10s"
tls_skip_verify = false

# VM configuration
[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

# LiteFS volume configuration
[mounts]
source = "litefs_data"
destination = "/var/lib/litefs"

# Static files configuration
[[statics]]
guest_path = '/code/staticfiles'
url_prefix = '/static/'

# Process groups
[processes]
app = "litefs mount"

# Machine restart policy
[[restart]]
policy = "on-failure"

# Deploy configuration
[deploy]
release_command = "/entrypoint.sh manage.py migrate"
strategy = "rolling"
