# Generated by Django 5.2 on 2025-04-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_location_campaign_npc_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='campaigns.campaign'),
        ),
    ]
