# Generated by Django 5.2 on 2025-04-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_chatmessage_confirmed_for_chapter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="description",
            new_name="generated_summary",
        ),
        migrations.AddField(
            model_name="campaign",
            name="user_description",
            field=models.TextField(blank=True),
        ),
    ]
