# Generated by Django 5.2 on 2025-05-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_chapterchatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=100)),
                ("character_name", models.CharField(max_length=100)),
                ("race", models.CharField(max_length=50)),
                ("character_class", models.CharField(max_length=50)),
                ("level", models.PositiveIntegerField(default=1)),
                ("background", models.CharField(blank=True, max_length=100)),
                ("alignment", models.CharField(blank=True, max_length=50)),
                ("passive_perception", models.PositiveIntegerField(default=10)),
                ("armor_class", models.PositiveIntegerField(default=10)),
                ("initiative_modifier", models.IntegerField(default=0)),
                ("current_hit_points", models.PositiveIntegerField(default=0)),
                ("notable_traits", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
    ]
