# Generated by Django 5.2 on 2025-05-04 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_charactersummary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="order",
            new_name="number",
        ),
        migrations.AddField(
            model_name="chapter",
            name="adventure_hook",
            field=models.TextField(
                default="adventure hook",
                help_text="Trigger or reason for party to start the chapter.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chapter",
            name="background",
            field=models.TextField(
                blank=True, help_text="World context and relevant history."
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="conclusion",
            field=models.TextField(
                blank=True, help_text="How the chapter ends and transitions forward."
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="dm_guidance",
            field=models.TextField(
                blank=True, help_text="Tips and guidance for running the chapter."
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="level_range",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="chapter",
            name="locations_description",
            field=models.TextField(
                blank=True,
                help_text="DM notes for locations, including read-aloud text and hidden details.",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="overview",
            field=models.TextField(
                default="overview",
                help_text="Brief summary of the chapter's events and objectives.",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("combat", "Combat"),
                            ("social", "Social"),
                            ("puzzle", "Puzzle"),
                            ("exploration", "Exploration"),
                            ("mixed", "Mixed/Other"),
                        ],
                        default="combat",
                        max_length=20,
                    ),
                ),
                ("level_range", models.CharField(blank=True, max_length=50)),
                (
                    "summary",
                    models.TextField(help_text="Purpose and context of the encounter."),
                ),
                (
                    "setup",
                    models.TextField(
                        help_text="Initial conditions and encounter details."
                    ),
                ),
                (
                    "read_aloud",
                    models.TextField(
                        help_text="Narrative for the DM to read to players."
                    ),
                ),
                (
                    "tactics",
                    models.TextField(
                        blank=True, help_text="Enemy strategy and dynamic notes."
                    ),
                ),
                (
                    "stat_blocks",
                    models.TextField(
                        blank=True, help_text="Stat blocks or reference notes."
                    ),
                ),
                (
                    "treasure",
                    models.TextField(
                        blank=True, help_text="Loot and rewards after the encounter."
                    ),
                ),
                (
                    "map_reference",
                    models.TextField(
                        blank=True,
                        help_text="Map or layout references for this encounter.",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="campaigns.chapter",
                    ),
                ),
            ],
        ),
    ]
