# Generated by Django 5.2 on 2025-05-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_encounter_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersummary',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='character_sub_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='heroic_inspiration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charactersummary',
            name='background',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='charactersummary',
            name='character_class',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
