# Generated by Django 5.2 on 2025-06-19 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_campaign_owner_chapter_owner_encounter_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionnote',
            name='chapter',
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='campaigns.encounter'),
        ),
    ]
