# Generated by Django 5.2 on 2025-06-20 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_remove_sessionnote_chapter_sessionnote_encounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionnote',
            old_name='notes',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='campaigns.encounter'),
        ),
    ]
