# Generated by Django 5.2 on 2025-06-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_rename_notes_sessionnote_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='number',
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order of the chapter in the campaign'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order of the encounter in the chapter'),
        ),
    ]
