# Generated by Django 5.2 on 2025-07-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_alter_chapter_options_alter_encounter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='level_range',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='stat_blocks',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='tactics',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='treasure',
        ),
        migrations.AddField(
            model_name='encounter',
            name='danger_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('deadly', 'Deadly')], help_text='At-a-glance danger estimation.', max_length=20),
        ),
        migrations.AddField(
            model_name='encounter',
            name='dm_notes',
            field=models.TextField(blank=True, help_text='All-purpose field: tactics, loot, stat block refs, etc.'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Tick this if the encounter is skippable or side content.'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='tags',
            field=models.CharField(blank=True, help_text="Optional tags like 'boss', 'undead', 'trap', 'ambush' (comma-separated)", max_length=200),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='map_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='read_aloud',
            field=models.TextField(blank=True, help_text='Optional boxed text or narration.'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='setup',
            field=models.TextField(blank=True, help_text='Scene setup, triggers, and conditions.'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='summary',
            field=models.TextField(help_text='Quick description of the encounter purpose.'),
        ),
    ]
