# Generated by Django 5.2 on 2025-07-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_remove_encounter_level_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='adventure_hook',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='background',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='dm_guidance',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='locations_description',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='overview',
        ),
        migrations.AddField(
            model_name='chapter',
            name='dm_notes',
            field=models.TextField(blank=True, help_text='Flexible notes: secrets, pacing tips, foreshadowing, etc.'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='intro',
            field=models.TextField(blank=True, help_text='Adventure hook or opening scene to kick things off.'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Mark this chapter as a side quest or optional content.'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='conclusion',
            field=models.TextField(blank=True, help_text='How the chapter wraps up or links to future chapters.'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='level_range',
            field=models.CharField(blank=True, help_text='E.g. Levels 4–5', max_length=50),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', help_text='Track campaign progress.', max_length=20),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='summary',
            field=models.TextField(blank=True, help_text='One-paragraph overview of the chapter’s purpose.'),
        ),
    ]
