# Generated by Django 5.2 on 2025-07-15 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_remove_chapter_adventure_hook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='summary',
            field=models.TextField(blank=True, help_text="One-paragraph overview of the chapter's purpose."),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('DM', 'Dungeon Master'), ('PLAYER', 'Player')], default='DM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself as a DM/Player')),
                ('preferred_name', models.CharField(blank=True, help_text="How you'd like to be addressed (optional)", max_length=100)),
                ('years_experience', models.PositiveIntegerField(blank=True, help_text='Years of experience as a DM (optional)', null=True)),
                ('favorite_systems', models.CharField(blank=True, help_text='Favorite RPG systems (e.g., D&D 5e, Pathfinder, etc.)', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
