# Generated by Django 5.2 on 2025-07-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_alter_chapter_summary_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_systems',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='years_experience',
        ),
    ]
