# Generated by Django 5.2 on 2025-07-17 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_remove_userprofile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('owner', 'Owner'), ('co_dm', 'Co-DM')], default='co_dm', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Collaborator',
                'verbose_name_plural': 'Campaign Collaborators',
                'unique_together': {('campaign', 'user')},
            },
        ),
    ]
