# Generated by Django 5.2 on 2025-07-31 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_playeravailability_sessionschedule_scheduledsession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ['name'], 'verbose_name': 'NPC', 'verbose_name_plural': 'NPCs'},
        ),
        migrations.AddField(
            model_name='npc',
            name='alignment',
            field=models.CharField(blank=True, choices=[('lawful_good', 'Lawful Good'), ('neutral_good', 'Neutral Good'), ('chaotic_good', 'Chaotic Good'), ('lawful_neutral', 'Lawful Neutral'), ('true_neutral', 'True Neutral'), ('chaotic_neutral', 'Chaotic Neutral'), ('lawful_evil', 'Lawful Evil'), ('neutral_evil', 'Neutral Evil'), ('chaotic_evil', 'Chaotic Evil'), ('unaligned', 'Unaligned')], help_text="The NPC's moral and ethical alignment", max_length=20),
        ),
        migrations.AddField(
            model_name='npc',
            name='appearance',
            field=models.TextField(blank=True, help_text='Physical description, clothing, distinctive features'),
        ),
        migrations.AddField(
            model_name='npc',
            name='chapters',
            field=models.ManyToManyField(blank=True, help_text='Chapters where this NPC is involved or appears', related_name='involved_npcs', to='campaigns.chapter'),
        ),
        migrations.AddField(
            model_name='npc',
            name='personality',
            field=models.TextField(blank=True, help_text='Personality traits, mannerisms, speech patterns, motivations'),
        ),
        migrations.AddField(
            model_name='npc',
            name='secret',
            field=models.TextField(blank=True, help_text='Hidden information, plot hooks, or secrets only the DM knows'),
        ),
        migrations.AddField(
            model_name='npc',
            name='stat_block',
            field=models.TextField(blank=True, help_text='Combat stats, abilities, and mechanical details (can be refined later)'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='description',
            field=models.TextField(blank=True, help_text='General description or notes'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Primary location where this NPC can be found', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.location'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='name',
            field=models.CharField(help_text="The NPC's full name", max_length=200),
        ),
        migrations.AlterField(
            model_name='npc',
            name='role',
            field=models.CharField(blank=True, help_text='Role in the story or society', max_length=100),
        ),
        migrations.AlterField(
            model_name='npc',
            name='status',
            field=models.CharField(choices=[('alive', 'Alive'), ('dead', 'Dead'), ('missing', 'Missing'), ('unknown', 'Unknown')], default='alive', help_text='Current status of the NPC', max_length=20),
        ),
        migrations.AlterField(
            model_name='npc',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags for organization (e.g., 'merchant, guild member, quest giver')", max_length=200),
        ),
    ]
