# Generated by Django 5.2 on 2025-07-31 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_alter_npc_options_npc_alignment_npc_appearance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='encounter',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The location where this encounter takes place', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='chapters',
            field=models.ManyToManyField(blank=True, help_text='Chapters where this location is featured or visited', related_name='involved_locations', to='campaigns.chapter'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, help_text='General description of the location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text="The location's name", max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, help_text='Geographic region or area', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags for organization (e.g., 'dungeon, city, tavern')", max_length=200),
        ),
    ]
