# Generated by Django 5.2 on 2025-07-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_alter_location_options_encounter_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='map_image',
        ),
        migrations.AddField(
            model_name='location',
            name='map_image',
            field=models.ImageField(blank=True, help_text='Optional map or visual reference for this location', upload_to='images/locations/'),
        ),
    ]
