# Generated by Django 5.2 on 2025-08-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0025_remove_encounter_map_image_location_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='actions',
            field=models.TextField(blank=True, help_text='Available actions in combat'),
        ),
        migrations.AddField(
            model_name='npc',
            name='armor_class',
            field=models.PositiveIntegerField(blank=True, help_text='Armor Class (AC)', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='challenge_rating',
            field=models.CharField(blank=True, help_text='Challenge Rating (e.g., 1/2, 2, 5)', max_length=10),
        ),
        migrations.AddField(
            model_name='npc',
            name='charisma',
            field=models.PositiveIntegerField(blank=True, help_text='Charisma score (1-30)', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='condition_immunities',
            field=models.CharField(blank=True, help_text='Condition immunities (e.g., charmed, frightened)', max_length=200),
        ),
        migrations.AddField(
            model_name='npc',
            name='constitution',
            field=models.PositiveIntegerField(blank=True, help_text='Constitution score (1-30)', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='creature_type',
            field=models.CharField(choices=[('humanoid', 'Humanoid'), ('beast', 'Beast'), ('monstrosity', 'Monstrosity'), ('dragon', 'Dragon'), ('fey', 'Fey'), ('fiend', 'Fiend'), ('celestial', 'Celestial'), ('undead', 'Undead'), ('construct', 'Construct'), ('elemental', 'Elemental'), ('giant', 'Giant'), ('aberration', 'Aberration'), ('ooze', 'Ooze'), ('plant', 'Plant')], default='humanoid', help_text="The creature's type (humanoid, beast, etc.)", max_length=20),
        ),
        migrations.AddField(
            model_name='npc',
            name='damage_immunities',
            field=models.CharField(blank=True, help_text='Damage immunities (e.g., poison, necrotic)', max_length=200),
        ),
        migrations.AddField(
            model_name='npc',
            name='damage_resistances',
            field=models.CharField(blank=True, help_text='Damage resistances (e.g., fire, cold)', max_length=200),
        ),
        migrations.AddField(
            model_name='npc',
            name='dexterity',
            field=models.PositiveIntegerField(blank=True, help_text='Dexterity score (1-30)', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='hit_dice',
            field=models.CharField(blank=True, help_text='Hit dice formula (e.g., 2d8+2)', max_length=50),
        ),
        migrations.AddField(
            model_name='npc',
            name='hit_points',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum hit points', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='intelligence',
            field=models.PositiveIntegerField(blank=True, help_text='Intelligence score (1-30)', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='languages',
            field=models.CharField(blank=True, help_text='Known languages (e.g., Common, Elvish)', max_length=200),
        ),
        migrations.AddField(
            model_name='npc',
            name='legendary_actions',
            field=models.TextField(blank=True, help_text='Legendary actions (if applicable)'),
        ),
        migrations.AddField(
            model_name='npc',
            name='proficiency_bonus',
            field=models.PositiveIntegerField(blank=True, help_text='Proficiency bonus (+2 to +9)', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='saving_throws',
            field=models.CharField(blank=True, help_text='Proficient saving throws (e.g., Dex +5, Wis +3)', max_length=200),
        ),
        migrations.AddField(
            model_name='npc',
            name='senses',
            field=models.CharField(blank=True, help_text='Special senses (e.g., darkvision 60 ft., passive Perception 13)', max_length=200),
        ),
        migrations.AddField(
            model_name='npc',
            name='size',
            field=models.CharField(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('huge', 'Huge'), ('gargantuan', 'Gargantuan')], default='medium', help_text="The creature's size category", max_length=20),
        ),
        migrations.AddField(
            model_name='npc',
            name='skills',
            field=models.CharField(blank=True, help_text='Proficient skills (e.g., Perception +5, Stealth +7)', max_length=300),
        ),
        migrations.AddField(
            model_name='npc',
            name='special_abilities',
            field=models.TextField(blank=True, help_text='Special abilities, traits, and features'),
        ),
        migrations.AddField(
            model_name='npc',
            name='speed',
            field=models.CharField(blank=True, help_text='Movement speeds (e.g., 30 ft., fly 60 ft.)', max_length=100),
        ),
        migrations.AddField(
            model_name='npc',
            name='strength',
            field=models.PositiveIntegerField(blank=True, help_text='Strength score (1-30)', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='wisdom',
            field=models.PositiveIntegerField(blank=True, help_text='Wisdom score (1-30)', null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='stat_block',
            field=models.TextField(blank=True, help_text='Legacy free-form stat block (use structured fields above instead)'),
        ),
    ]
