# Generated by Django 5.2 on 2025-08-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0026_npc_actions_npc_armor_class_npc_challenge_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='description',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='stat_block',
        ),
    ]
