# Generated by Django 5.2 on 2025-08-02 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0028_enemy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom name for this combat session', max_length=200)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='setup', max_length=20)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('current_turn', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rounds', models.PositiveIntegerField(default=0)),
                ('initiative_rolled', models.BooleanField(default=False)),
                ('dm_notes', models.TextField(blank=True, help_text='DM notes during combat')),
                ('combat_summary', models.TextField(blank=True, help_text='Summary of what happened in this combat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_sessions', to='campaigns.encounter')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CombatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('player', 'Player Character'), ('enemy', 'Enemy'), ('ally', 'Ally NPC')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('current_hp', models.IntegerField()),
                ('max_hp', models.IntegerField()),
                ('temp_hp', models.IntegerField(default=0)),
                ('initiative_roll', models.IntegerField(blank=True, null=True)),
                ('initiative_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('position_x', models.IntegerField(blank=True, null=True)),
                ('position_y', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Combat notes for this participant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.charactersummary')),
                ('enemy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.enemy')),
                ('combat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='campaigns.combatsession')),
            ],
            options={
                'ordering': ['initiative_order'],
            },
        ),
        migrations.CreateModel(
            name='CombatAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('attack', 'Attack'), ('damage', 'Damage'), ('heal', 'Healing'), ('spell', 'Spell'), ('move', 'Movement'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('value', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='campaigns.combatparticipant')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_actions', to='campaigns.combatparticipant')),
                ('combat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='campaigns.combatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect_type', models.CharField(choices=[('condition', 'Condition'), ('buff', 'Buff'), ('debuff', 'Debuff'), ('spell', 'Spell Effect')], default='condition', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_rounds', models.IntegerField(blank=True, null=True)),
                ('rounds_remaining', models.IntegerField(blank=True, null=True)),
                ('affects_attack', models.BooleanField(default=False)),
                ('affects_damage', models.BooleanField(default=False)),
                ('affects_saves', models.BooleanField(default=False)),
                ('affects_movement', models.BooleanField(default=False)),
                ('auto_damage_per_turn', models.IntegerField(default=0)),
                ('auto_healing_per_turn', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_effects', to='campaigns.combatparticipant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
