# Generated by Django 5.2 on 2025-08-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0029_combatsession_combatparticipant_combataction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='npcs',
            field=models.ManyToManyField(blank=True, help_text='NPCs that appear in this specific encounter', related_name='encounters', to='campaigns.npc'),
        ),
    ]
