# Generated by Django 5.2 on 2025-08-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0030_encounter_npcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='chapters',
            field=models.ManyToManyField(blank=True, help_text='Chapters where this enemy is involved or appears', related_name='involved_enemies', to='campaigns.chapter'),
        ),
    ]
