# Generated by Django 5.2 on 2025-08-04 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0031_enemy_chapters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersummary',
            name='blinded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='charmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='deafened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='frightened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='grappled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='incapacitated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='invisible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='maximum_hit_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='paralyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='petrified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='poisoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='prone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='restrained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='stunned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersummary',
            name='unconscious',
            field=models.BooleanField(default=False),
        ),
    ]
