# Generated by Django 5.2.7 on 2025-10-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0032_add_character_conditions_and_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='map_reference',
            field=models.TextField(blank=True, help_text='Notes about map location, grid coordinates, or other spatial references'),
        ),
    ]
