# Generated by Django 5.2.7 on 2025-10-24 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0033_change_map_reference_to_textfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadAloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title or label for this read-aloud section (e.g., 'Opening Scene', 'When they enter the room')", max_length=200)),
                ('text', models.TextField(help_text='The descriptive text to read aloud to players')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of this read-aloud in the encounter')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_alouds', to='campaigns.encounter')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_alouds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Read-Aloud',
                'verbose_name_plural': 'Read-Alouds',
                'ordering': ['order'],
            },
        ),
    ]
