# Generated by Django 5.2.7 on 2025-10-30 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0033_change_map_reference_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionschedule',
            name='include_weekdays',
            field=models.BooleanField(default=False, help_text='Include weekdays in scheduling options'),
        ),
        migrations.AddField(
            model_name='sessionschedule',
            name='slot_duration_hours',
            field=models.PositiveIntegerField(default=2, help_text='Duration of each time slot in hours'),
        ),
        migrations.AddField(
            model_name='sessionschedule',
            name='slot_overlap_hours',
            field=models.PositiveIntegerField(default=0, help_text='Hours of overlap between consecutive slots (0 for no overlap)'),
        ),
        migrations.AddField(
            model_name='sessionschedule',
            name='weekday_end_time',
            field=models.TimeField(default=datetime.time(22, 0), help_text='End time for weekday availability (e.g., 22:00)'),
        ),
        migrations.AddField(
            model_name='sessionschedule',
            name='weekday_start_time',
            field=models.TimeField(default=datetime.time(19, 0), help_text='Start time for weekday availability (e.g., 19:00)'),
        ),
        migrations.AddField(
            model_name='sessionschedule',
            name='weekend_end_time',
            field=models.TimeField(default=datetime.time(22, 0), help_text='End time for weekend availability (e.g., 22:00)'),
        ),
        migrations.AddField(
            model_name='sessionschedule',
            name='weekend_start_time',
            field=models.TimeField(default=datetime.time(12, 0), help_text='Start time for weekend availability (e.g., 12:00)'),
        ),
    ]
