# Generated by Django 5.2.7 on 2025-11-01 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0034_sessionschedule_include_weekdays_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionschedule",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="sessionschedule",
            name="session_duration",
        ),
        migrations.AlterField(
            model_name="sessionschedule",
            name="date_range_end",
            field=models.DateField(
                default=datetime.date(2025, 11, 29),
                help_text="End of the date range for potential sessions",
            ),
        ),
        migrations.AlterField(
            model_name="sessionschedule",
            name="date_range_start",
            field=models.DateField(
                default=datetime.date(2025, 11, 1),
                help_text="Start of the date range for potential sessions",
            ),
        ),
        migrations.AlterField(
            model_name="sessionschedule",
            name="include_weekdays",
            field=models.BooleanField(
                default=True, help_text="Include weekdays in scheduling options"
            ),
        ),
        migrations.AlterField(
            model_name="sessionschedule",
            name="slot_duration_hours",
            field=models.PositiveIntegerField(
                default=3, help_text="Duration of each time slot in hours"
            ),
        ),
        migrations.AlterField(
            model_name="sessionschedule",
            name="slot_overlap_hours",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Hours of overlap between consecutive slots (0 for no overlap)",
            ),
        ),
    ]
