# Generated by Django 5.2.7 on 2025-11-01 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0035_remove_sessionschedule_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionschedule",
            name="date_range_end",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 11, 29, 15, 44, 55, 204175, tzinfo=datetime.timezone.utc
                ),
                help_text="End of the date range for potential sessions",
            ),
        ),
        migrations.AlterField(
            model_name="sessionschedule",
            name="date_range_start",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 11, 1, 15, 44, 55, 204156, tzinfo=datetime.timezone.utc
                ),
                help_text="Start of the date range for potential sessions",
            ),
        ),
    ]
