# Generated by Django 5.2.7 on 2025-11-01 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0036_alter_sessionschedule_date_range_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionschedule",
            name="date_range_end",
            field=models.DateField(
                default=datetime.date(2025, 11, 29),
                help_text="End of the date range for potential sessions",
            ),
        ),
        migrations.AlterField(
            model_name="sessionschedule",
            name="date_range_start",
            field=models.DateField(
                default=datetime.date(2025, 11, 1),
                help_text="Start of the date range for potential sessions",
            ),
        ),
    ]
